name: lint and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run go fmt (check mode)
        run: |
          if [ "$(gofmt -l . | wc -l)" -ne 0 ]; then
            echo "Go files are not properly formatted:"
            gofmt -l .
            exit 1
          fi

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run go test
        run: |
          go test ./...
